#!/usr/bin/env bash
# Installs a GoogleService-Info.plist downloaded from the Firebase console as the
# per-environment options file the app actually loads.
#
# FirebaseRuntimeConfiguration looks up "<environment>.firebase" in the app
# bundle, so the console's file has to be renamed before the app can see it.
# Getting that wrong is silent: the app just renders the "setup required"
# screen. This script validates the file up front and says what is wrong.
#
# Usage: scripts/install_firebase_config.sh <GoogleService-Info.plist> [environment]
#        environment defaults to "production" (what Release builds load).

set -euo pipefail

readonly BUNDLE_ID="com.syntholo.ios"
readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "usage: $0 <GoogleService-Info.plist> [production|staging|development]" >&2
    exit 2
fi

source_plist="$1"
environment="${2:-production}"

case "$environment" in
    production|staging|development) ;;
    *)
        echo "error: unknown environment '$environment'" >&2
        echo "       expected production, staging, or development" >&2
        exit 2
        ;;
esac

if [[ ! -f "$source_plist" ]]; then
    echo "error: no such file: $source_plist" >&2
    exit 1
fi

read_key() {
    /usr/libexec/PlistBuddy -c "Print :$1" "$source_plist" 2>/dev/null || true
}

api_key="$(read_key API_KEY)"
project_id="$(read_key PROJECT_ID)"
gcm_sender_id="$(read_key GCM_SENDER_ID)"
google_app_id="$(read_key GOOGLE_APP_ID)"
plist_bundle_id="$(read_key BUNDLE_ID)"
reversed_client_id="$(read_key REVERSED_CLIENT_ID)"
client_id="$(read_key CLIENT_ID)"

fail() {
    echo "error: $1" >&2
    echo "       Re-download the iOS config from the Firebase console:" >&2
    echo "       Project settings -> Your apps -> iOS -> GoogleService-Info.plist" >&2
    exit 1
}

# These mirror hasRequiredFirebaseValues in FirebaseRuntimeConfiguration.swift.
# Failing here beats shipping a build that boots to the setup-required screen.
[[ -n "$project_id" ]] || fail "PROJECT_ID is missing or empty"
[[ -n "$google_app_id" ]] || fail "GOOGLE_APP_ID is missing or empty"

[[ "$api_key" =~ ^A[A-Za-z0-9_-]{38}$ ]] \
    || fail "API_KEY is not a 39-character key beginning with 'A'"

[[ "$gcm_sender_id" =~ ^[0-9]{6,20}$ ]] \
    || fail "GCM_SENDER_ID is not 6-20 digits"

IFS=':' read -r app_prefix app_sender app_platform app_suffix <<< "$google_app_id"
[[ "$app_prefix" =~ ^[0-9]+$ ]] \
    || fail "GOOGLE_APP_ID first component is not numeric"
[[ "$app_sender" == "$gcm_sender_id" ]] \
    || fail "GOOGLE_APP_ID sender '$app_sender' does not match GCM_SENDER_ID '$gcm_sender_id'"
[[ "$app_platform" == "ios" ]] \
    || fail "GOOGLE_APP_ID is for platform '$app_platform', not 'ios'"
[[ "$app_suffix" =~ ^[0-9a-fA-F]+$ ]] \
    || fail "GOOGLE_APP_ID last component is not hexadecimal"

if [[ -n "$plist_bundle_id" && "$plist_bundle_id" != "$BUNDLE_ID" ]]; then
    fail "config is for bundle id '$plist_bundle_id', but this app is '$BUNDLE_ID'"
fi

destination="$REPO_ROOT/Syntholo/Resources/${environment}.firebase.plist"
cp "$source_plist" "$destination"
echo "installed $environment config -> Syntholo/Resources/${environment}.firebase.plist"
echo "  project: $project_id"

# Google sign-in reads its client id from the build settings, not this plist.
if [[ -n "$reversed_client_id" && -n "$client_id" ]]; then
    cat > "$REPO_ROOT/Config/Firebase.local.xcconfig" <<EOF
// Generated by scripts/install_firebase_config.sh from $environment config.
GOOGLE_CLIENT_ID = $client_id
GOOGLE_REVERSED_CLIENT_SCHEME = $reversed_client_id
EOF
    echo "wrote Config/Firebase.local.xcconfig for Google sign-in"
else
    echo "note: no CLIENT_ID in the config, so Google sign-in stays unconfigured."
    echo "      Enable Google as a sign-in provider in the Firebase console and"
    echo "      re-download the plist if you want that button to work."
fi

echo
echo "Next: regenerate the project so the new file is bundled."
echo "  xcodegen generate"
